---
- hosts: all
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker,dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io

  - name: Install pip
    apt:
      name: python-pip
      state: present
      update_cache: yes

  - name: Install ansible pip dependecies
    pip:
      name: "{{ modules }}"
    vars:
      modules:
      - requests
      - docker

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  - name: Pull an image
    docker_image:
      name: tomcat:latest
      source: pull

  - name: Download a+ opensource repo
    git:
      repo: 'https://github.com/jbpadgett/hello-world-repo.git'
      dest: /tmp/repo

  - name: Copy premade war
    copy:
      src: /tmp/repo/java/war-tomcat/hello.war
      dest: /tmp/docker/
      remote_src: yes

  - name: Build myApp's image
    docker_image:
      name: myapp
      tag: 1.0.0
      build:
        path: /tmp/docker
        pull: no
      source: build
      push: no
      archive_path: /tmp/archive.tgz

  - name: Copy Image so can deploy it..
    synchronize:
      mode: pull
      src: /tmp/archive.tgz
      dest: /tmp/docker/myimage.tgz

